language: c
env:
  - NODE_VERSION="5"
  - NODE_VERSION="4"
  - NODE_VERSION="0.12"
os:
  - linux
  - osx
before_install:
  - rm -rf ~/.nvm/
  - git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
install:
  - npm install
script:
  - npm run test
after_script:
  - npm run coveralls
sudo: false
